# 1. Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad_db
spring.datasource.username=postgres
spring.datasource.password=ROOT

# 2. Configuración de Hibernate (El asistente que crea las tablas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Seguridad inicial (Para que no nos bloquee todo de entrada)
# Esto nos servirá para probar que la app corre
spring.security.user.name=admin
spring.security.user.password=admin123
